packages:
  - packages/*

ignoredBuiltDependencies:
  - '@scarf/scarf'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - core-js-pure
  - esbuild
  - tree-sitter
  - tree-sitter-json

patchedDependencies:
  '@phosphor-icons/react@2.1.10': patches/@phosphor-icons__react@2.1.10.patch
